---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backfront-deployment
  labels:
    app: backfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backfront
  template:
    metadata:
      name: backfront
      labels:
        app: backfront
    spec:
      containers:
      - name: backend
        image: tabwizard/backend:latest
        ports:
        - containerPort: 9000
      - name: frontend
        image: tabwizard/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-app
spec:
  selector:
    matchLabels:
      app: db-app
  serviceName: "db"
  replicas: 1
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: news
          - name: PGDATA
            value: "/data/pgdata"
            
