---              
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stage
  labels:
    app: frontend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      nodePort: 30088
  type: NodePort
  selector:
    app: backfront   
    
---              
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stage
  labels:
    app: backend
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: backfront   
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backfront-deployment
  namespace: stage
  labels:
    app: backfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backfront
  template:
    metadata:
      name: backfront
      labels:
        app: backfront
    spec:
      containers:
      - name: backend
        image: tabwizard/backend:latest
        ports:
        - containerPort: 9000
      - name: frontend
        image: tabwizard/frontend:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: stage
  labels:
    app: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db-app        
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-app
  namespace: stage
  labels:
    app: db-app
spec:
  selector:
    matchLabels:
      app: db-app
  serviceName: "db"
  replicas: 1
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: news
          - name: PGDATA
            value: "/data/pgdata"
            
