---
- name: Role Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic

- name: Role Install Kibana
  hosts: kibana
  roles:
    - kibana-role

- name: Role Install Filebeat
  hosts: filebeat
  roles:
    - filebeat-role
