all:
  hosts:
    cp:
      ansible_host: 35.86.59.86
      ip: 172.31.49.59
    node1:
      ansible_host: 35.82.15.110
      ip: 172.31.58.254
    node2:
      ansible_host: 35.87.71.112
      ip: 172.31.60.103
    node3:
      ansible_host: 44.226.206.215
      ip: 172.31.59.229
    node4:
      ansible_host: 44.234.114.157
      ip: 172.31.56.124
  children:
    kube_control_plane:
      hosts:
        cp:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
