---
elasticsearch:
  hosts:
    elastic-vm:
      ansible_host: 192.168.178.91
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
kibana:
  hosts:
    kibana-vm:
      ansible_host: 192.168.178.92
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
