apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: front
    image: nginx
    volumeMounts:
    - name: shared
      mountPath: /static
  - name: backend
    image: alpine
    volumeMounts:
    - name: shared
      mountPath: /static
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
