# -*- mode: ruby -*-
# vi: set ft=ruby :

node = {
  '1' => 'elastic-vm',
  '2' => 'kibana-vm',
  '3' => 'logstash-vm' 
}

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  node.each do |i,x|
    config.vm.define x do |n|
      n.vm.hostname = x
      n.vm.network "public_network", bridge: "enp3s0", auto_config: false
      n.vm.provider :virtualbox do |vb|
          vb.memory = 512
      end    
      n.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub;"
      n.vm.provision "shell" do |s|
        s.inline = "mkdir ~/.ssh;"\
          "touch ~/.ssh/authorized_keys;"\
          "cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys;"\
          "chmod 700 /root/.ssh;"\
          "chmod 600 /root/.ssh/authorized_keys;"\
          "rm -rf /tmp/id_rsa.pub;"\
          "ip addr add $1 dev eth1;"\
          "ip link set dev eth1 up;"
        s.args = ["192.168.178.9#{i}/24"]
      end
    end
  end
end
