FROM node

RUN apt-get update && apt-get install git

RUN cd && git clone https://github.com/simplicitesoftware/nodejs-demo.git

WORKDIR /root/nodejs-demo

RUN npm install

ENV VCAP_APP_HOST=0.0.0.0
ENV VCAP_APP_PORT=3000

EXPOSE 3000

ENTRYPOINT ["npm", "start"]
