FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget gnupg openjdk-11-jdk sudo && apt-get clean; rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -

RUN sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'

RUN apt-get update && apt-get install -y jenkins && apt-get clean; rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY start_jenkins.sh /usr/bin/start_jenkins.sh

RUN chmod +x /usr/bin/start_jenkins.sh

EXPOSE 8080

ENTRYPOINT ["/usr/bin/start_jenkins.sh"]
