FROM node:alpine

RUN apk add --no-cache --virtual .build-deps-yarn git

RUN cd && git clone https://github.com/simplicitesoftware/nodejs-demo.git

WORKDIR /root/nodejs-demo

RUN npm install

EXPOSE 3000

ENTRYPOINT ["npm", "start"]
