apiVersion: v1
kind: Pod
metadata:
  name: fedora-configmap
spec:
  containers:
  - name: fedora-configmap
    image: fedora:latest
    command: ['/bin/bash', '-c']
    args: ["sleep 60000"]
    env:
    - name: DOMAIN_NAME
      valueFrom:
        configMapKeyRef:
          name: domain
          key: name
    envFrom:
    - configMapRef:
        name: domain
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      name: nginx-config
