apiVersion: v1
kind: Pod
metadata:
  name: vault-fedora
spec:
  containers:
  - name: vault-fedora
    image: fedora:latest
    command: ['/bin/bash', '-c']
    args: ["sleep 60000"]
    env:
      - name: VAULT_TOKEN
        valueFrom:
          secretKeyRef:
            name: vault-token
            key: token
  restartPolicy: Never