---
all:
  hosts:
    el-instance:
      ansible_host: 178.154.195.77
    kbn-instance:
      ansible_host: 178.154.195.127
    flb-instance:
      ansible_host: 178.154.195.69
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_user: wizard
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    kbn-instance:
filebeat:
  hosts:
    flb-instance:
