apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-testuser
  namespace: app-namespace
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "describe"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
