apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-testuser
  namespace: app-namespace
subjects:
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-testuser
  apiGroup: rbac.authorization.k8s.io 
