apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: mytestapp
spec:
  environments:
    stage:
      defaultNamespace: stage
      server: https://10.0.0.10:6443
    prod:
      defaultNamespace: prod
      server: https://10.0.0.10:6443
      includes:
        - endpoint
  vars: {}
  excludes:
    - endpoint
  
