all:
  hosts:
    cp:
      ansible_host: 52.40.87.243
      ip: 10.0.101.199
    node1:
      ansible_host: 34.214.52.39
      ip: 10.0.101.12
  children:
    kube_control_plane:
      hosts:
        cp:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        cp:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
